# Kubernetes Secrets Template
# Replace placeholder values and apply with: kubectl apply -f secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: jarvis-secrets
  namespace: jarvis
type: Opaque
stringData:
  # Database connection string
  # Format: postgresql://username:password@host:port/database
  database-url: "postgresql://jarvis_user:CHANGEME@postgres.jarvis.svc.cluster.local:5432/jarvis"

  # Redis connection string
  # Format: redis://host:port or redis://:password@host:port
  redis-url: "redis://redis.jarvis.svc.cluster.local:6379"

  # API keys and secrets (if needed)
  api-key: "CHANGEME"

  # Azure AD OAuth credentials (for NextAuth)
  azure-ad-client-id: "CHANGEME"
  azure-ad-client-secret: "CHANGEME"
  azure-ad-tenant-id: "CHANGEME"

  # NextAuth secret (generate with: openssl rand -base64 32)
  nextauth-secret: "CHANGEME"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jarvis-env-config
  namespace: jarvis
data:
  # Application environment
  NODE_ENV: "production"

  # Logging configuration
  LOG_LEVEL: "INFO"

  # Service URLs
  NEXTAUTH_URL: "https://jarvis.frontier.audio"
  API_URL: "https://api.jarvis.frontier.audio"

  # Temporal configuration
  TEMPORAL_HOST: "temporal.jarvis.svc.cluster.local:7233"

  # Performance tuning
  MAX_WORKERS: "4"
  REQUEST_TIMEOUT: "30000"

  # Feature flags
  ENABLE_VOICE_SESSIONS: "true"
  ENABLE_OFFLINE_FALLBACK: "true"
